### PR TITLE
Fix handling of {Primal,Dual}Status

### LINKED ISSUE #249: Incorrect PrimalStatus if termination is not optimal
Juniper reports the `PrimalStatus` as `INFEASIBLE_POINT` when the problem is not optimal:
https://github.com/lanl-ansi/Juniper.jl/blob/053661ebc023ff4534210207f9ca40c0ff42fca0/src/MOI_wrapper/results.jl#L29-L39

This is incorrect, because sometimes the point is actually feasible. If we can prove feasibility, it should be `FEASIBLE_POINT`, otherwise it should be something like `UNKNOWN_RESULT_STATUS`

First reported on Discourse:
https://discourse.julialang.org/t/obtaining-sub-optimal-results-from-the-model-when-the-time-limit-is-reached/85635

### PR DESCRIPTION
**Pull request by odow**
Closes #249

### CODE REVIEW

**Comment by odow** [comment]
The `DualStatus` thing is another surprise. I think I recall people trying to use Juniper with SDDP.jl and getting weird errors, so perhaps this was the reason.

**Comment by Wikunia** [comment]
I'm happy to get this merged is there anything you would like to add or can this be merged @odow ?

**Comment by ccoffrin** [comment]
@odow, also should we add a note to the changelog?

**Comment by odow** [comment]
Yes, I'll add and prep a new release.

**Pull request merged**
