### PR TITLE
Prep for v0.9.0 release

### PR DESCRIPTION
**Pull request by odow**

### CODE REVIEW

**Comment by odow** [comment]
That looks like some sort of race condition:
image

**Comment by ccoffrin** [comment]
So you think a Julia bug?

**Comment by odow** [comment]
Could be some weird parallelism thing? I haven't dived into how Juniper does things. I'll restart the CI and see if we hit it again. If it comes up again we can investigate further.

**Comment by ccoffrin** [comment]
Seemed to work now.

**Pull request merged**
