### PR TITLE
Fix failures with MOI unit tests

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by blegat** [comment]
Note that CI passes, it is red only because it fails to push to codecov:
https://travis-ci.org/github/lanl-ansi/Juniper.jl/jobs/758540329#L926

**Comment by Wikunia** [comment]
Thanks @blegat 
We might wanna move over to GitHub actions anyway @ccoffrin ?

**Comment by ccoffrin** [comment]
We should get the CI working with coverage. I am a fan of moving over to github actions.

**Comment by blegat** [comment]
Maybe defer that to a separate PR ?

**Comment by Wikunia** [comment]
Will do in: #208 I merge this thanks @blegat for fixing the tests.

**Pull request merged**
