### PR TITLE
disable fpump in optimize! when all options are set

### PR DESCRIPTION
**Pull request by Wikunia**
Bugfix for not using fpump if mip solver exists @ccoffrin

### CODE REVIEW

**Comment by ccoffrin** [comment]
Should we add a test?

**Comment by ccoffrin** [comment]
LGTM

**Comment by Wikunia** [comment]
This should probably be directly 0.6.1, right? I'll add it to the changelog then and register a new version once the tests passed.

**Comment by ccoffrin** [comment]
Yes.  All bug fixes should be patched.

**Pull request merged**
