### PR TITLE
Delete untested files in /test

### LINKED ISSUE #227: CI for MINLPTests
It doesn't look like these are actually tested?
https://github.com/lanl-ansi/Juniper.jl/tree/master/test/MINLPTests

AmplNLWriter has a separate CI job:
https://github.com/jump-dev/AmplNLWriter.jl/blob/master/.github/workflows/minlptests.yml

### PR DESCRIPTION
**Pull request by odow**
Closes #227 

@ccoffrin not sure what you want to do with these.

There's a circular dependency with Juniper and MINLPTests. For now I've removed the MINLPTests.jl file from Juniper because it wasn't being tested in CI.

We could remove the Juniper test from MINLPTests.jl, and add a MINLPTest here instead?

### CODE REVIEW

**Comment by ccoffrin** [comment]
How is the circular dependency managed with Ipopt.jl?

**Comment by odow** [comment]
Ipopt doesn't run MINLPTests

**Comment by ccoffrin** [comment]
In that case, I say we drop MINLPTests from Juniper to avoid the circular dep.  We can try to improve MOI-tests if we find issues, right?

Re the other tests:
- We can drop the PowerModels ones, these are from a bygone era when JuMP testing infrastructure was not so nice
- `current_118.jl` looks like a test for the function registration interface.  Which should now be covered by `FP: no linear`

@Wikunia any objections in dropping `current_118.jl`?

**Comment by odow** [comment]
Judging by the syntax, it doesn't seem like the `current_118` file has ever really been tested. And yes, the registration stuff is now covered by other tests.

**Comment by odow** [comment]
Merging for now. We can re-add the `current_118` if @Wikunia objects.

**Comment by ccoffrin** [comment]
Sounds good to me!

**Pull request merged**
