### PR TITLE
Restore randomnes after optimizing with Juniper.

### PR DESCRIPTION
**Pull request by tweisser**
In order to get reproducible results, Juniper sets  `Random.seed!` at some few places. This makes `rand()` basically useless, when used in a loop together with Juniper:
```julia
vals = zeros(10)
for i = 1:10
    m = some_model_generating_function(rand(); model = Model(Juniper.Optimizer()))
    optimize!(m)
    vals[i] = objective_value(m)
end
```
The entries of `vals[2:10]` are all the same. This is because when calling `optimize!` for the first time, Juniper sets the seed and hence, when calling `rand()` afterwards, it will always return the same number. 

This PR resolves the problem by storing a random number before setting the seed and resetting the seed to this random number,  before returning a solution.

### CODE REVIEW

**Comment by Wikunia** [comment]
Thanks for opening the issue. I'm wondering whether the best option would be to create an own random number generator like.

```
const JUNIPER_RNG = MersenneTwister(1);
```

and then call `rand(JUNIPER_RNG, ...)` that would make sure that it doesn't interfere with the outside system in any way. What do you think @tweisser & @ccoffrin

**Comment by tweisser** [comment]
Your suggestions is much cleaner than what I did. I pushed the changes.

**Comment by Wikunia** [comment]
Great! Does it still work as expected on your side?

**Comment by tweisser** [comment]
Yes, it does. I added a test in test/basic.jl.Maybe you have a better place for the test?

**Comment by Wikunia** [comment]
No I think that is an appropriate test case.

**Comment by tweisser** [comment]
Sorry, no time to help with the Ipopt issue...

**Comment by Wikunia** [comment]
No worries thanks for this PR. I've just opened an issue #192 for that. Will work on it hopefully tmr. Then I can merge your PR and register a new version.

Thanks again!

**Comment by ccoffrin** [comment]
@Wikunia, thanks for the suggestion of a dedicated number generator.  I was going to make the same one.  :-)

Changes look good to me.  There should be a way for the user to set the internal seed as well (to allow testing the impact of the seed on solver performance), but this can be filed as a feature issue outside of this PR.

**Comment by odow** [comment]
> There should be a way for the user to set the internal seed as well

If I'm not mistaken, you should be able to go
```Julia
Random.seed!(Juniper.JUNIPER_RNG, 1234)
```

**Comment by Wikunia** [comment]
Oh yeah that should work @odow that is very neat!

**Comment by ccoffrin** [comment]
Good point!  We just need to document this constant `JUNIPER_RNG`. 

We might also consider exposing it as a solver parameter as well.  I think this is where most users are used to setting the seed of a solver.

**Comment by Wikunia** [comment]
Don't get the problem with code coverage here. LGTM

**Comment by ccoffrin** [comment]
LGTM, I say go for it.  Make sure to take a note in the change log.

**Pull request merged**
