### PR TITLE
WIP Jump v0.21

### PR DESCRIPTION
**Pull request by Wikunia**
Needs testing for `optimizer_with_attributes` which will also remove the deprecation warnings. But maybe can be used for testing in PowerModels @ccoffrin

### CODE REVIEW

**Comment by Wikunia** [comment]
Some weird local infeasible test set now. Any ideas @ccoffrin ?

**Comment by Wikunia** [comment]
Will fail on Travis because there JuMP v0.20.1 is used...

**Comment by Wikunia** [comment]
we can merge this once Travis is done if you want @ccoffrin and add MINLPTests later again. Currently MINLPTests doesn't seem to be compatible with JuMP v0.21

**Comment by ccoffrin** [comment]
Should the version be v0.6.0?  it is not clear to me that the changes to the parameters are backward compatible.

**Comment by Wikunia** [comment]
Oh true thanks. My mistake.

**Comment by ccoffrin** [comment]
LGTM, I say we merge.  I will then test PowerModels with the master branch.

**Pull request merged**
