### PR TITLE
WIP: Run one node on two processors

### PR DESCRIPTION
**Pull request by Wikunia**
First implementation of #138

### CODE REVIEW

**Comment by Wikunia** [comment]
Options for regression testing

- standard (check that there is no change to master)
- 4 processors

Missing is a restart if almost solved and integral but not allowed, but this should be an option anyway.

**Comment by Wikunia** [comment]
Has problems with some instances but this is the first run against master and #134 (with 1 proc more)
Screenshot from 2019-06-04 10-32-49

**Comment by ccoffrin** [comment]
This is what I expected.  When using the pmap, adding extra processes
results in a significant warmup overhead around 10-30 seconds.

Some options that come to mind,
- don’t use multiple threads by default, but provide setting suggestions in
the reader for solving medium/large problems.
- explore if Julia Threads can be used instead of Distribute
- design some very rough problem metrics that can be used to only add
processes on larger / harder problems when where there warmup time will
have a smaller impact of total runtime.

**Comment by Wikunia** [comment]
The overhead you mention isn't there if we do a precompile run, right?
The slow start happens only on the strong parallel branching part and I'm not sure why that is the case atm.
Regarding the suggestions yes I can check some rough metrics. Additionally we can run the relaxation in parallel as well but start with the feasibility pump if one of them is done. Then we might be able to get a better relaxed solution due to random starting positions. That said the feasibility pump is quite fast for small problems so there the overhead will be always visible.

**Comment by Wikunia** [comment]
At what stage of the solver should we decide this? I am wondering whether this should be determined before the relaxation or after. I think the relaxation time might be a good indicator but this is only true if we know whether Ipopt was called before or not. Is there a way to find it out?

**Comment by ccoffrin** [comment]
I would probably do before solving the relaxation and just use the number of variables and constraints.  Some combination of those two properties should be a strong indicator if the problem will be solved very quickly or not.  If that is problematic then I would add the time required to solve the root node relaxation and a third criteria to consider.

**Comment by Wikunia** [comment]
One problem might be that one of the two sub-problems needs longer than the other such that one processor is idle which isn't the case in the standard parallel approach. There we might have the problem that we go into branches which aren't useful but no processor is idle.

**Comment by ccoffrin** [comment]
closing due to lack of progress.

**Pull request closed without merging**
