### PR TITLE
Bugfix when optimizer without attributes

### PR DESCRIPTION
**Pull request by Wikunia**
Bugfix for #201 

This converts the optimizer to an optimizer with attributes in all cases.
Haven't added a test for this yet as it creates quite some output from Ipopt.

### CODE REVIEW

**Comment by Wikunia** [comment]
Do you mind to check this as well @umbe0 ?
@ccoffrin I would like to figure out why the code coverage fails in quite a lot of cases before merging. Do you think it's okay to not have a test for this as the log would be quite huge or can you think of a way to not print it to the stdout?

**Comment by umbe0** [comment]
Hi @Wikunia, I updated the Juniper package and I tried to execute my optimization with the setting
`m = Model(with_optimizer(Juniper.Optimizer;
nl_solver = with_optimizer(Ipopt.Optimizer),
                mip_solver = with_optimizer(Cbc.Optimizer)))`
but the same error keeps coming out.

**Comment by Wikunia** [comment]
Hi @umbe0 thanks for trying it out. It's not merged and tagged yet. You have to install it via
```
(@v1.5) pkg> add Juniper#bugfix-optimizer_constructor
```

Thanks again!

**Comment by umbe0** [comment]
Ah, sorry, I did not know.
Anyway, I followed your indication and, at least in my case, it run correctly! The solver reaches convergence providing all the outputs and no error message.
Thank you very much!

**Comment by ccoffrin** [comment]
@Wikunia, regarding the test.  It is possible to capture stdout and stderr so that you will not see the solver's output.  For example you can look at how it is done here,

https://github.com/JuliaOpt/Pajarito.jl/blob/master/test/qptest.jl

But I am also open to the idea of not having an explicit test for this case.  We might think about adding it to MINLPTests.jl, as it is part of testing the JuMP API.

**Comment by Wikunia** [comment]
I've added a test case. But have no idea why codecov is failing.

**Pull request merged**
